import 'src/scss/globals.scss';
import type { Metadata } from 'next';
import { Montserrat, Space_Grotesk } from 'next/font/google';

const space_grotesk = Space_Grotesk({
	variable: '--font-grotesk',
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'pwr explorer',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://pro.fontawesome.com/releases/v5.15.4/css/all.css"
					rel="stylesheet"
				/>
			</head>
			<body className={space_grotesk.className}>{children}</body>
		</html>
	);
}
